добавил модалку кнопки buy now
Andrey1914/ice-cream pull request #13
Opened 2022-04-02 17:29 UTC by realtrueluv

2022-04-03 07:28 UTC, Andrey1914 requested changes
4 строка- не правильно написан класс. Получился блок__элемент__элемент. Должно быть блок__элемент--модификатор (модификатор если нужно что- то видоизменить)
14 строка- спан в лейбле, но имя родительского блока модал, а не форм-модал. Тоже самое со всеми спанами до строки 46.
Обрати, пожалуйста, внимание на именование классов.

2022-04-03 08:00 UTC, Andrey1914 requested changes
4 строка- напиши, пожалуйста class="modal__icon"

2022-04-03 08:08 UTC, 1-Serg-1 requested changes
data-modal просто атрибут ="" лишнее
По наименованию классов есть моменты:
Первое - наименование, где в стилях есть маржин, может быть только модификатор, то есть блок__элемент--модификатор. Модификатор можно вешать и просто на блок (блок--модификатор)
Второе - вчера я понял, что у нас у всех есть немного отличий в наименовании классов по БЭМ, предлагаю, чтобы убрать споры (а они как правило будут находится в кнопках и модалке/форме), взять как основу предложение Андрея (тимлида) по названию спорных элементов. Если не понятно, лучше задать вопрос напрямую Андрею.

2022-04-04 09:52 UTC, Andrey1914 approved these changes

2022-04-04 09:53 UTC, closed without merging