Добавляет стили в Contacts
Andrey1914/ice-cream pull request #23
Opened 2022-04-03 15:03 UTC by IrynaLaptieva

Добавляет стили в Contacts

2022-04-03 15:13 UTC, Andrey1914 requested changes
Используйте, пожалуйста, конкатенацию селекторов. Вот пример: 
.section {
  width: 100%;

  &__title {
    color: red;
  }

  &__text {
    font-size: 14px;
  }
}

2022-04-03 17:54 UTC, IrynaLaptieva commented
> Используйте, пожалуйста, конкатенацию селекторов. Вот пример: .section { width: 100%;
> 
> &__title { color: red; }
> 
> &__text { font-size: 14px; } }

Исправила

2022-04-03 20:56 UTC, AleksandrTikka approved these changes

2022-04-03 20:57 UTC, AleksandrTikka approved these changes

2022-04-04 05:01 UTC, Andrey1914 approved these changes

2022-04-04 05:01 UTC, merged